#spring:
#  profiles: container
#  datasource:
#    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}
#    initialize: true

spring:
  profiles: container
  datasource:
    url: jdbc:mysql://demo-mysql:3306/demo
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
    platform: mysql

